# Generated by Django 3.2.3 on 2022-06-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='url',
        ),
        migrations.AddField(
            model_name='picture',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
